<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>accesoCreacionDeAutorizaciones</name>
   <tag></tag>
   <elementGuidId>79c31334-9fea-44c1-ae13-279cc92997a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>a[href='/Autorizaciones/Nueva']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>a[href='/Autorizaciones/Nueva']</value>
   </webElementProperties>
</WebElementEntity>
