<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>campoUsuario</name>
   <tag></tag>
   <elementGuidId>a05c94ef-b46c-4f0a-bd47-f457873c1086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#Username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#Username</value>
   </webElementProperties>
</WebElementEntity>
