<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>campoComentarioCancelacionAutorizacion</name>
   <tag></tag>
   <elementGuidId>16b4f3bf-ac86-499c-8b6c-c576c758fa85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>textarea[name='comentario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>textarea[name='comentario']</value>
   </webElementProperties>
</WebElementEntity>
