<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>campoTelefonoDelAfiliado</name>
   <tag></tag>
   <elementGuidId>848eb455-ed03-4ba1-85f4-87b6dacd2ae2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>input[name='telefono-afiliado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>input[name='telefono-afiliado']</value>
   </webElementProperties>
</WebElementEntity>
