<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>campoCorreoElectronicoAfiliado</name>
   <tag></tag>
   <elementGuidId>c7411728-3411-4f95-881d-71ce3d1b428a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>input[name='correo-afiliado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>input[name='correo-afiliado']</value>
   </webElementProperties>
</WebElementEntity>
